rngdopresp = phased.RangeDopplerResponse(...
        'DopplerFFTLengthSource','Property',...
        'DopplerFFTLength',1024,...
        'DopplerOutput','Speed',...
        'OperatingFrequency',450e6,...
        'SampleRate',fs,...
        'PropagationSpeed',3e8);