lfm = phased.LinearFMWaveform('SampleRate',fs,...
    'PulseWidth',30e-6,'PRF',1e3,...
    'SweepBandwidth',100e3,'SweepDirection','Up',...
    'Envelope','Rectangular',...
    'OutputFormat','Pulses','NumPulses',1);
wav = lfm();