lfm = phased.LinearFMWaveform('SampleRate',fs,...
    'PulseWidth',45e-6,'PRF',10e3,...
    'SweepBandwidth',100e3,'SweepDirection','Up',...
    'Envelope','Rectangular',...
    'OutputFormat','Pulses','NumPulses',1);
wav = lfm();